// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbdqhvhxyhzmxdpdlitk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZHFodmh4eWh6bXhkcGRsaXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3OTkyMzYsImV4cCI6MjA3NjM3NTIzNn0.QBGpEidgbgB4FgTTazmEWx0tEINUn2pCh5kTNlzt4oU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});